include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  errors:
    invalid_use_of_protected_member: error
    missing_required_param: error
    missing_return: error
    dead_code: error
    invalid_annotation_target: ignore
    # Allow dynamic in some cases for flexibility
    avoid_dynamic_calls: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "build/**"

linter:
  rules:
    # Documentation: Enable for core/domain layers, relaxed for features
    # Set to 'info' to encourage docs without breaking builds
    # For stricter enforcement, change to 'warning' or remove this line
    public_member_api_docs: info
    lines_longer_than_80_chars: false
    # Allow some flexibility in sorting
    sort_pub_dependencies: false
    # Immutability best practice - prevents accidental parameter reassignment
    # Must disable avoid_final_parameters to enable prefer_final_parameters
    avoid_final_parameters: false
    prefer_final_parameters: true
