"use client";

import React, { useState } from "react";
import { format } from "date-fns";
import { Loader2 } from "lucide-react";
import {
  useGetFinanceStatsQuery,
  useGetRecentTransactionsQuery,
} from "../../../../redux/features/api/dashboard/admin/dashboard/adminDashboardApi";

export default function AdminFinanceClient() {
  const [activeTab, setActiveTab] = useState("overview");
  const [statusFilter, setStatusFilter] = useState<string>("ALL");

  const { data: statsData, isLoading: isStatsLoading } =
    useGetFinanceStatsQuery();
  const { data: txData, isLoading: isTxLoading } =
    useGetRecentTransactionsQuery({ limit: 10 });

  const stats = statsData?.data || {
    totalRevenue30Days: 0,
    pendingPayoutsAmount: 0,
    pendingPayoutsCount: 0,
    failedTransactionsCount: 0,
  };

  const recentTransactions = txData?.data?.items || [];

  const filteredTransactions = recentTransactions.filter((tx: any) =>
    statusFilter === "ALL" ? true : tx.status === statusFilter,
  );

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="font-['Nunito',sans-serif] font-bold text-[24px] leading-8 text-[#282828]">
          Finance & Payments
        </h1>
        <p className="font-['Arial',sans-serif] text-[14px] leading-5 text-[#62748e] mt-1">
          Manage platform revenue, monitor transactions, and handle vendor
          payouts.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white border border-[#e5e7eb] rounded-xl p-6 flex flex-col gap-2 shadow-sm">
          <p className="font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
            Total Revenue (30 Days)
          </p>
          <h2 className="font-['Nunito',sans-serif] font-bold text-[28px] text-[#282828]">
            {isStatsLoading ? (
              <span className="inline-block w-32 h-8 bg-gray-200 rounded animate-pulse" />
            ) : (
              `$${(stats.totalRevenue30Days ?? 0).toFixed(2)}`
            )}
          </h2>
          <p className="font-['Arial',sans-serif] text-[12px] text-[#00c950] font-medium">
            Generated by platform fees
          </p>
        </div>
        <div className="bg-white border border-[#e5e7eb] rounded-xl p-6 flex flex-col gap-2 shadow-sm">
          <p className="font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
            Pending Payouts
          </p>
          <h2 className="font-['Nunito',sans-serif] font-bold text-[28px] text-[#282828]">
            {isStatsLoading ? (
              <span className="inline-block w-32 h-8 bg-gray-200 rounded animate-pulse" />
            ) : (
              `$${(stats.pendingPayoutsAmount ?? 0).toFixed(2)}`
            )}
          </h2>
          <p className="font-['Arial',sans-serif] text-[12px] text-[#fe9a00] font-medium">
            {stats.pendingPayoutsCount ?? 0} vendors awaiting payment
          </p>
        </div>
        <div className="bg-white border border-[#e5e7eb] rounded-xl p-6 flex flex-col gap-2 shadow-sm">
          <p className="font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
            Failed Transactions
          </p>
          <h2 className="font-['Nunito',sans-serif] font-bold text-[28px] text-[#282828]">
            {isStatsLoading ? (
              <span className="inline-block w-20 h-8 bg-gray-200 rounded animate-pulse" />
            ) : (
              stats.failedTransactionsCount
            )}
          </h2>
          <p className="font-['Arial',sans-serif] text-[12px] text-red-500 font-medium">
            Requires immediate attention
          </p>
        </div>
      </div>

      <div className="bg-white border border-[#e5e7eb] rounded-xl w-full flex flex-col overflow-hidden">
        <div className="flex border-b border-[#e5e7eb] px-6 pt-2 bg-[#f8fafc]">
          {["overview", "transactions", "payouts"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-3 font-['Nunito',sans-serif] font-medium text-[15px] capitalize transition-colors relative ${
                activeTab === tab
                  ? "text-[#00c950]"
                  : "text-[#62748e] hover:text-[#282828]"
              }`}
            >
              {tab}
              {activeTab === tab && (
                <div className="absolute -bottom-px left-0 right-0 h-0.5 bg-[#00c950]"></div>
              )}
            </button>
          ))}
        </div>

        <div className="p-6">
          <div className="flex justify-between items-center mb-4">
            <h3 className="font-['Nunito',sans-serif] font-bold text-[18px] text-[#282828] capitalize">
              Recent {activeTab}
            </h3>
            <div className="flex items-center gap-2">
              {["ALL", "SUCCESS", "PENDING", "FAILED"].map((s) => (
                <button
                  key={s}
                  onClick={() => setStatusFilter(s)}
                  className={`px-3 py-1 text-[11px] font-bold rounded-full transition-all capitalize ${
                    statusFilter === s
                      ? s === "SUCCESS"
                        ? "bg-[#00c950] text-white"
                        : s === "PENDING"
                          ? "bg-[#fe9a00] text-white"
                          : s === "FAILED"
                            ? "bg-red-500 text-white"
                            : "bg-gray-800 text-white"
                      : "bg-gray-100 text-gray-500 hover:bg-gray-200"
                  }`}
                >
                  {s === "ALL" ? "All" : s.charAt(0) + s.slice(1).toLowerCase()}
                </button>
              ))}
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-[#e5e7eb]">
                  <th className="pb-3 pt-4 px-4 font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
                    ID
                  </th>
                  <th className="pb-3 pt-4 px-4 font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
                    DATE
                  </th>
                  <th className="pb-3 pt-4 px-4 font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
                    PAYER
                  </th>
                  <th className="pb-3 pt-4 px-4 font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
                    TYPE
                  </th>
                  <th className="pb-3 pt-4 px-4 font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
                    AMOUNT
                  </th>
                  <th className="pb-3 pt-4 px-4 font-['Nunito',sans-serif] font-medium text-[14px] text-[#62748e]">
                    STATUS
                  </th>
                </tr>
              </thead>
              <tbody>
                {isTxLoading ? (
                  <tr>
                    <td colSpan={6} className="py-10 text-center">
                      <div className="flex justify-center">
                        <Loader2 className="w-8 h-8 animate-spin text-[#00c950]" />
                      </div>
                    </td>
                  </tr>
                ) : filteredTransactions.length === 0 ? (
                  <tr>
                    <td
                      colSpan={6}
                      className="py-10 text-center text-gray-400 font-medium"
                    >
                      No{" "}
                      {statusFilter === "ALL"
                        ? ""
                        : statusFilter.toLowerCase() + " "}
                      transactions found.
                    </td>
                  </tr>
                ) : (
                  filteredTransactions.map((tx: any) => (
                    <tr
                      key={tx.id}
                      className="border-b border-[#f1f5f9] hover:bg-[#f8fafc] transition-colors"
                    >
                      <td className="py-4 px-4 font-['Arial',sans-serif] text-[14px] text-[#0f172b] font-medium">
                        {tx.transactionId}
                      </td>
                      <td className="py-4 px-4 font-['Arial',sans-serif] text-[14px] text-[#62748e]">
                        {format(new Date(tx.createdAt), "MMM dd, yyyy")}
                      </td>
                      <td className="py-4 px-4 font-['Arial',sans-serif] text-[14px] text-[#0f172b]">
                        {tx.payerName}
                      </td>
                      <td className="py-4 px-4 font-['Arial',sans-serif] text-[14px] text-[#0f172b]">
                        {tx.method || "System"}
                      </td>
                      <td className="py-4 px-4 font-['Arial',sans-serif] text-[14px] font-bold text-[#00c950]">
                        ${(tx.amount ?? 0).toFixed(2)}
                      </td>
                      <td className="py-4 px-4">
                        <span
                          className={`px-2 py-1 text-[12px] font-bold rounded-full ${
                            tx.status === "SUCCESS"
                              ? "bg-[#e2f8eb] text-[#00c950]"
                              : tx.status === "PENDING"
                                ? "bg-[#fff5e5] text-[#fe9a00]"
                                : "bg-[#fee2e2] text-red-600"
                          }`}
                        >
                          {tx.status}
                        </span>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
